name: make-main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: |
          sudo apt-get update
          sudo apt-get install libcdio-dev libcdio-cdda-dev libcdio-paranoia-dev json-glib-tools libjson-c-dev libiso9660-dev libudf-dev git gcc g++ cmake pkg-config qtbase5-dev libtag1-dev libgcrypt-dev libusb-1.0-0-dev flex bison clang-tidy
          git clone https://github.com/rigomate/libcue.git
          pushd libcue
          mkdir build && cd build && cmake .. && cmake --build . && sudo make install
          popd
          git submodule update --init --recursive
          mkdir build && cd build && cmake .. -DRUN_CLANG_TIDY=ON && cmake --build .
      - name: Process clang-tidy warnings
        uses: asarium/clang-tidy-action@v1
        with:
          fixesFile: build/clang-fixes.yaml